/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tobi' at '17.10.15 17:22' with Gradle 2.6
 *
 * @author tobi, @date 17.10.15 17:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
